services:
  nginx:
    image: nginx:1.30-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./static:/usr/share/nginx/html/static:ro
    networks:
      - dummynet
    restart: unless-stopped

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - dummy-volume:/var/lib/postgresql/data
    networks:
      - dummynet
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    
  app:
    build: .
    expose:
      - "8111"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:mysecretpassword@postgres:5432/postgres
    networks:
      - dummynet
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v3.5.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    networks:
      - dummynet
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:v1.9.1
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --path.rootfs=/rootfs
      - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - dummynet
    restart: unless-stopped

  grafana:
    image: grafana/grafana:12.2.0
    ports:
      - "3000:3000"
    networks:
      - dummynet
    restart: unless-stopped

volumes:
  dummy-volume:
    external: true

networks:
  dummynet:
    external: true
